development:
  host: localhost
  database: sencha_touch_notes_development
  include_root_in_json: true
  
test:
  host: localhost
  database: sencha_touch_notes_test

# set these environment variables on your prod server
production:
  host: localhost
  database: sencha_touch_notes_development
  include_root_in_json: true
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
